### ISSUE TITLE
namespaces problem on IOS

### ISSUE THREAD

**Issue by juanitozambada** [naderio/nativescript-socket.io#33]
@naderio 

I'm using the plugin nativescript-socket.io which uses:
socket.io-client-swift version 11.0

pod 'Socket.IO-Client-Swift', '~> 11.0'

  and I can not work with namespaces. However, you can work with namespaces about:

socket.io-client-swift version 12.1.1 onwards ...

Could you do something about it?

**Comment by naderio** [comment]
@juanitozambada this plugin iOS supports namespace .. unless it doesn't  anymore.

```javascript
const socketio = SocketIO.connect('http://somewhere/namespace', options);
```
anyhow, socket.io-client-swift v12+ seems to break this plugin (see issue  #31) so won't be upgraded unless iOS implementation is rechecked.

would you kindly run the demo on iOS? if so make sure to use the right ip address instead of `192.168.1.111`

**Comment by naderio** [comment]
@juanitozambada did you manage to have namespace working?
