### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by bloodf** [naderio/nativescript-socket.io#56]
Is this plugin deprecated or abandoned?

**Comment by naderio** [comment]
@bloodf not necessarily either. current status is as follows:

- Android implementation is fully operational and up to date 
- iOS implementation is lagging behind due to changes introduced by Xcode/Swift, for which this plugin supports Swift v2.3, and [Socket.IO-Client-Swift](https://github.com/socketio/socket.io-client-swift/blob/master/CHANGELOG.md), for which this plugin supports v11 
  - it seems most users are upgrading to Swift 4 which requires Socket.IO-Client-Swift v12+
  - upgrade to Socket.IO-Client-Swift v12+ have been attempted bust it seems to break build and features for some use case

Anyhow, I'm working on getting this plugin verified which might require a rewrite anyhow.

In all cases, any contribution/PR is welcome.
